language: python

python:
  - "3.6"
  - "3.8"

addons:
  apt:
    update: true
    sources:
      - llvm-toolchain-trusty-7
      - ubuntu-toolchain-r-test
    packages:
      - clang-8
      - gcc-8

install:
  - pip install coveralls
  - pip install -r requirements.txt

script:
  - coverage run --source=cantools setup.py test
  - make test-sdist
  - env PYTHONPATH=. python examples/hello_world.py
  - env PYTHONPATH=. python examples/diagnostics/did.py
  - make test-c-clean ; fi
  - make test-c ; fi
  - make test-c-clean ; fi
  - CC=gcc-8 make test-c ; fi
  - make test-c-clean ; fi
  - CC=clang-8 make test-c-src ; fi

after_success:
  coveralls
