language: python

python:
  - "2.7"
  - "3.6"
  - "3.8"

addons:
  apt:
    update: true
    sources:
      - llvm-toolchain-trusty-7
      - ubuntu-toolchain-r-test
    packages:
      - clang-7
      - gcc-8

install:
  - pip install coveralls
  - pip install -r requirements.txt

script:
  - coverage run --source=cantools setup.py test
  - make test-sdist
  - env PYTHONPATH=. python examples/hello_world.py
  - env PYTHONPATH=. python examples/diagnostics/did.py
  - if [[ "$(python --version)" =~ "Python 3" ]] ; then make test-c ; fi
  - if [[ "$(python --version)" =~ "Python 3" ]] ; then CC=gcc-8 make test-c ; fi
  - if [[ "$(python --version)" =~ "Python 3" ]] ; then CC=clang-7 make test-c ; fi

after_success:
  coveralls
